name: Dotnet Build project.

on: 
  push:
    branches:
      - '*'
env: 
  GITHUB_PACKAGES_TOKEN : ${{ secrets.GITHUB_PACKAGES_TOKEN }}
  GITHUB_PACKAGES_USER : ${{ secrets.GITHUB_PACKAGES_USER }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
        dotnet restore --configfile nuget.config
        dotnet build --configuration Release
        dotnet test
