name: Package Into Nuget Library

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release
        dotnet pack  --configuration Release
         
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'
    
    - name: Push package to the Github Package Registry
      run: |
        nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/kth-me/index.json" -UserName kth-me -Password ${{ secrets.GITHUB_TOKEN }}
        nuget setApiKey ${{ secrets.NUGET_API_KEY }} -Source "GitHub"
        nuget push bin/Release/*.nupkg -Source "GitHub" -SkipDuplicate
